[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FC8019"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1A1A2E"
font = "sans serif"
